- name: Incluir variables
  include_vars: common.yml

- name: Actualizar fuentes
  apt: update_cache=yes

- name: Instalar paquetes
  apt:
    pkg: "{{ packages }}"
    state: present
  
- name: Configuracion Postfix - main.cf
  template: src=main.j2 dest=/etc/postfix/main.cf owner=root group=root mode=0644

- name: Configuracion Postfix - sasl_passwd
  template: src=sasl_passwd.j2 dest=/etc/postfix/sasl_passwd owner=root group=root mode=0600

- name: Configuracion Postfix - postmap sasl_passwd
  shell: '/usr/sbin/postmap hash:/etc/postfix/sasl_passwd'

- name: Configuracion Postfix - permisos sasl_passwd
  file: path=/etc/postfix/sasl_passwd owner=root group=root mode=0600

- name: Configuracion Postfix - generic mapping
  template: src=generic.j2 dest=/etc/postfix/generic owner=root group=root mode=0600

- name: Configuracion Postfix - postmap generic mapping
  shell: '/usr/sbin/postmap hash:/etc/postfix/generic'

- name: Reiniciar postfix
  service: name=postfix state=restarted